name: Java CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # adjust based on your project

    - name: Build with Maven
      run: mvn clean package

    - name: Archive WAR file
      uses: actions/upload-artifact@v4
      with:
        name: app-war
        path: target/*.war
